# Generated by Django 3.0.4 on 2020-06-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200616_1122'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressandpayment',
            name='order_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.Order'),
            preserve_default=False,
        ),
    ]
