# Generated by Django 3.0.4 on 2020-06-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_addressandpayment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressandpayment',
            name='order_id',
        ),
    ]
