# Generated by Django 3.0.4 on 2020-06-18 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200616_1122'),
        ('checkout', '0008_auto_20200618_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressandpayment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressandpayment',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.Order'),
        ),
    ]
