# Generated by Django 3.0.4 on 2020-06-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20200618_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressandpayment',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
