# Generated by Django 3.0.4 on 2020-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20200618_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressandpayment',
            name='accountnumber',
        ),
        migrations.AddField(
            model_name='addressandpayment',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='addressandpayment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addressandpayment',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
