# Generated by Django 3.0.4 on 2020-07-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20200716_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressandpayment',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
