# Generated by Django 3.0.4 on 2020-07-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200716_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressandpayment',
            name='amount',
        ),
    ]
