# Generated by Django 3.0.4 on 2020-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_addressandpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressandpayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
