# Generated by Django 3.0.4 on 2020-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_addressandpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressandpayment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
