# Generated by Django 3.0.4 on 2020-04-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20200402_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.CharField(choices=[('Food Crops', (('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Dal', 'Dal'), ('Maize', 'Maize'), ('Pulses', 'Pulses'), ('Millets', 'Millets'))), ('Cash Crops', (('Sugarcane', 'Sugarcane'), ('Tobacco', 'Tobacco'), ('Cotton', 'Cotton'))), ('Plantation Crops', (('Coffee', 'Coffee'), ('Coconut', 'Coconut'), ('Tea', 'Tea')))], max_length=200, verbose_name='Crop'),
        ),
    ]
