# Generated by Django 3.0.4 on 2020-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20200402_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='total_land_available',
            field=models.DecimalField(decimal_places=2, help_text='In Acres', max_digits=5, verbose_name='Total land owned'),
        ),
    ]
