# Generated by Django 3.0.4 on 2020-04-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20200402_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='expecting_yield',
            field=models.DecimalField(decimal_places=2, help_text='In Quintal', max_digits=5, null=True, verbose_name='Yield Expecting'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='land_cultivating',
            field=models.DecimalField(decimal_places=2, help_text='In Acres', max_digits=5, verbose_name='Land planning to cultivate'),
        ),
    ]
