# Generated by Django 3.0.4 on 2020-07-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20200402_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='water_source',
            field=models.CharField(choices=[('River', 'River'), ('Drilled Well', 'Drilled Well'), ('Drainage ponds', 'Drainage ponds'), ('Rain Water', 'Rain Water')], default='Rain Water', max_length=100, verbose_name='Water Source'),
        ),
    ]
