# Generated by Django 3.0.3 on 2020-03-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='Agriculture', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Farm.jpg', upload_to='blog_pics'),
        ),
    ]
