# Generated by Django 3.0.4 on 2020-07-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200324_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
